theme = "monokai_soda"

[editor]
auto-format = true
auto-pairs = false
bufferline = "always"
cursor-shape.insert = "bar"
file-picker.hidden = false
indent-guides.character = "╎"
indent-guides.render = true
inline-diagnostics.cursor-line = "warning"
insert-final-newline = true
lsp.display-inlay-hints = true
lsp.display-messages = true
rulers = [80, 100]
soft-wrap.enable = true
statusline.left = ["mode", "spinner", "file-name"]
statusline.right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
true-color = true
whitespace.characters.newline = "¬"
whitespace.characters.tab = "·"
whitespace.characters.tabpad = "·"
whitespace.render.newline = "all"
whitespace.render.tab = "all"

[keys.normal]
"up"    = ["keep_primary_selection","delete_selection","move_line_up","paste_before"]
"down"  = ["keep_primary_selection","delete_selection","paste_after"]
"left"  = "unindent"
"right" = "indent"
"C-x" = ":reset-diff-change"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.insert."C-v"]
"tab" = [":insert-output printf \\\\t", "move_char_right"]
