theme = "monokai_soda"

[editor]
auto-format = true
auto-pairs = false
bufferline = "always"
rulers = [80, 100]
soft-wrap.enable = true
true-color = true
insert-final-newline = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "·"
newline = "¬"
tabpad = "·"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
"up"    = ["keep_primary_selection","delete_selection","move_line_up","paste_before"]
"down"  = ["keep_primary_selection","delete_selection","paste_after"]
"left"  = "unindent"
"right" = "indent"
