theme = "monokai_soda"

[editor]
auto-format = true
true-color = true
rulers = [80, 100]
bufferline = "always"
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "·"
newline = "¬"
tabpad = "·"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
"up"= ["keep_primary_selection","extend_line","yank","move_line_up","open_above","normal_mode","replace_with_yanked", "move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
"down" = ["keep_primary_selection","extend_line","delete_selection", "paste_after", "move_line_down"]
"left" = "unindent"
"right" = "indent"
