[language-server.vscode-json-language-server.config.format]
insertFinalNewline = true

[language-server.gopls.config]
gofumpt = true
codelenses.gc_details = true

[language-server.spicedb]
command = "spicedb"
args = ["lsp", "--log-level=trace"]

[language-server.rust-analyzer.config]
cargo.buildScripts.enable = true
checkOnSave.command = "clippy"

[[language]]
name = "spicedb"
# language-servers = ["spicedb"]
