---
name: "Container"
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "docker/build-push-action@v2"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: false
      - uses: "docker/build-push-action@v2"
        if: "${{ github.ref == 'refs/heads/main' }}"
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "ghcr.io/${{ github.repository }}:latest"
